
/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.0087
    # angle_max: 1.5708
    # angle_min: -1.5708
    angle_max: 1.5708
    angle_min: -1.5708
    inf_epsilon: 1.0
    max_height: 0.2
    min_height: 0.05
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 16
    range_max: 4.0
    range_min: 0.15
    scan_time: 0.3333
    target_frame: cloud
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: false
